### ISSUE TITLE
Running on Linux exits if Qt5 is not installed on the system

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-geoprocessor-python#176]
The GeoProcessor, when downloaded and run on Debian Linux Jessie complained with the following:

```
~/gptest-1.1.0-venv/scripts$ ./gptestui
operatingSystem=linux (used to check for Cygwin and filemode compatibility)
Using DISPLAY=:0.0 for X Windows server.
Checking for whether Python virtual environment (venv) needs to be 
activated...
Appear to be running in venv
VIRTUAL_ENV is not set.  Activating the venv.

Running the geoprocessor for Python3...
Traceback (most recent call last):
   File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
     "__main__", mod_spec)
   File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File 
"/home/clane/gptest-1.1.0-venv/lib/python3.4/site-packages/geoprocessor/app/gp.py", 
line 33, in <module>
     from PyQt5.QtWidgets import QApplication
ImportError: libQt5Widgets.so.5: cannot open shared object file: No such 
file or directory
```

**Comment by smalers** [comment]
It appears that Qt5 was not installed on the operating system.  This is one issue with Python virtual environments - they containerize Python applications but don't containerize operating system programs and libraries.

Need to figure out if there is a way to provide an intelligent warning to the user but this may be difficult because the exception occurs in an import that is not wrapped with a try.  The module could be loaded dynamically but that could get ugly.  Maybe there needs to be a function called at the beginning of the main application to see if modules are available, and if not, print a warning before going to other code.  It depends on what gets loaded in what order.  At a minimum, add some troubleshooting documentation.

**Comment by smalers** [comment]
Installing Qt5 worked.  See the [discussion of how to install here](https://www.howtoinstall.co/en/debian/jessie/qt5-default).  Still need to update the user documentation troubleshooting section.  It may be difficult to handle in the script given the separation of components.
