### ISSUE TITLE
Cannot run GeoProcessor in PyCharm

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-geoprocessor-python#321]
The `scripts/gpdev.bat` batch files can be used to run the GeoProcessor in development environment, and uses the files from the repository working files.  PyCharm finds files needed in import statements and allows editing code fine.  However, trying to run `geoprocessor/app/gp.py` using the right-click ***Run*** button shows the following error.  The environment as configured with `build-util/run-pycharm-ce-for-qgis.bat`, which is used to start PyCharm, must not be getting fully passed to the run tool.  One option is to run `gpdev.bat` from PyCharm, but this is not much more convenient than running the batch file directly and may not provide access to debugging, etc. 

```
C:\Users\sam\owf-dev\GeoProcessor\git-repos\owf-app-geoprocessor-python\venv\venv-qgis-3.10-python37\Scripts\python.exe C:/Users/sam/owf-dev/GeoProcessor/git-repos/owf-app-geoprocessor-python/geoprocessor/app/gp.py
Traceback (most recent call last):
  File "C:/Users/sam/owf-dev/GeoProcessor/git-repos/owf-app-geoprocessor-python/geoprocessor/app/gp.py", line 39, in <module>
    from geoprocessor.commands.testing.StartRegressionTestResultsReport import StartRegressionTestResultsReport
  File "C:\Users\sam\owf-dev\GeoProcessor\git-repos\owf-app-geoprocessor-python\geoprocessor\commands\testing\StartRegressionTestResultsReport.py", line 31, in <module>
    import geoprocessor.util.validator_util as validator_util
  File "C:\Users\sam\owf-dev\GeoProcessor\git-repos\owf-app-geoprocessor-python\geoprocessor\util\validator_util.py", line 27, in <module>
    import ogr
  File "C:\Program Files\QGIS 3.10\apps\Python37\Lib\site-packages\ogr.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "C:\Program Files\QGIS 3.10\apps\Python37\Lib\site-packages\osgeo\__init__.py", line 41, in <module>
    _gdal = swig_import_helper()
  File "C:\Program Files\QGIS 3.10\apps\Python37\Lib\site-packages\osgeo\__init__.py", line 24, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified procedure could not be found.

Process finished with exit code 1
```

**Comment by smalers** [comment]
This issue has been fixed in issue #326 and developer documentation has also been updated.  Close the issue.
